# HTTP Server
[server]
Address = ":8888"
AccessLogEnabled = true
ErrorLogEnabled = true
LogPath = "./logs/server"
DumpRouterMap = true

# Logger
[logger]
Path = "./logs/log"
Level = "all"
Stdout = true

# MySQL 配置
[database]
# 默认启动Mysql配置
[database.default]
Host = "127.0.0.1"
Port = "3306"
User = "root"
Pass = "gdkid,,.."
Name = "gf-vue-admin"
Type = "mysql"
Role = ""
Debug = true
Prefix = ""
DryRun = ""
Charset = "utf8"
Weight = ""
MaxIdle = ""
MaxOpen = ""
MaxLifetime = ""

# 测试环境Mysql配置
[database.test]
Host = "127.0.0.1"
Port = "3306"
User = "root"
Pass = "gdkid,,.."
Name = "gf-vue-admin-test"
Type = "mysql"
Debug = true
Prefix = ""
DryRun = ""
Charset = "utf8"
Weight = ""
MaxIdle = ""
MaxOpen = ""
MaxLifetime = ""

# Database logger.
[database.logger]
Path = "./logs/sql"
Level = "all"
Stdout = true

# Redis 配置
[redis]
default = "127.0.0.1:6379,1,?idleTimeout=600"
cache = "127.0.0.1:6379,2,?idleTimeout=600"
